### YamlMime:ManagedReference
items:
- uid: RealtyHub.ApiService.Configuration
  commentId: T:RealtyHub.ApiService.Configuration
  id: Configuration
  parent: RealtyHub.ApiService
  children:
  - RealtyHub.ApiService.Configuration.ContractTemplatesPath
  - RealtyHub.ApiService.Configuration.ContractsPath
  - RealtyHub.ApiService.Configuration.CorsPolicyName
  - RealtyHub.ApiService.Configuration.EmailSettings
  - RealtyHub.ApiService.Configuration.LogosPath
  - RealtyHub.ApiService.Configuration.PhotosPath
  - RealtyHub.ApiService.Configuration.ReportsPath
  langs:
  - csharp
  - vb
  name: Configuration
  nameWithType: Configuration
  fullName: RealtyHub.ApiService.Configuration
  type: Class
  source:
    remote:
      path: Codigos/RealtyHub/RealtyHub.ApiService/Configuration.cs
      branch: main
      repo: https://github.com/israel-bsi/realtyhub
    id: Configuration
    path: ../RealtyHub.ApiService/Configuration.cs
    startLine: 2
  assemblies:
  - RealtyHub.ApiService
  namespace: RealtyHub.ApiService
  syntax:
    content: public class Configuration
    content.vb: Public Class Configuration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: RealtyHub.ApiService.Configuration.CorsPolicyName
  commentId: F:RealtyHub.ApiService.Configuration.CorsPolicyName
  id: CorsPolicyName
  parent: RealtyHub.ApiService.Configuration
  langs:
  - csharp
  - vb
  name: CorsPolicyName
  nameWithType: Configuration.CorsPolicyName
  fullName: RealtyHub.ApiService.Configuration.CorsPolicyName
  type: Field
  source:
    remote:
      path: Codigos/RealtyHub/RealtyHub.ApiService/Configuration.cs
      branch: main
      repo: https://github.com/israel-bsi/realtyhub
    id: CorsPolicyName
    path: ../RealtyHub.ApiService/Configuration.cs
    startLine: 4
  assemblies:
  - RealtyHub.ApiService
  namespace: RealtyHub.ApiService
  syntax:
    content: public const string CorsPolicyName = "realtyhub"
    return:
      type: System.String
    content.vb: Public Const CorsPolicyName As String = "realtyhub"
- uid: RealtyHub.ApiService.Configuration.ContractsPath
  commentId: P:RealtyHub.ApiService.Configuration.ContractsPath
  id: ContractsPath
  parent: RealtyHub.ApiService.Configuration
  langs:
  - csharp
  - vb
  name: ContractsPath
  nameWithType: Configuration.ContractsPath
  fullName: RealtyHub.ApiService.Configuration.ContractsPath
  type: Property
  source:
    remote:
      path: Codigos/RealtyHub/RealtyHub.ApiService/Configuration.cs
      branch: main
      repo: https://github.com/israel-bsi/realtyhub
    id: ContractsPath
    path: ../RealtyHub.ApiService/Configuration.cs
    startLine: 5
  assemblies:
  - RealtyHub.ApiService
  namespace: RealtyHub.ApiService
  syntax:
    content: public static string ContractsPath { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property ContractsPath As String
  overload: RealtyHub.ApiService.Configuration.ContractsPath*
- uid: RealtyHub.ApiService.Configuration.PhotosPath
  commentId: P:RealtyHub.ApiService.Configuration.PhotosPath
  id: PhotosPath
  parent: RealtyHub.ApiService.Configuration
  langs:
  - csharp
  - vb
  name: PhotosPath
  nameWithType: Configuration.PhotosPath
  fullName: RealtyHub.ApiService.Configuration.PhotosPath
  type: Property
  source:
    remote:
      path: Codigos/RealtyHub/RealtyHub.ApiService/Configuration.cs
      branch: main
      repo: https://github.com/israel-bsi/realtyhub
    id: PhotosPath
    path: ../RealtyHub.ApiService/Configuration.cs
    startLine: 6
  assemblies:
  - RealtyHub.ApiService
  namespace: RealtyHub.ApiService
  syntax:
    content: public static string PhotosPath { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property PhotosPath As String
  overload: RealtyHub.ApiService.Configuration.PhotosPath*
- uid: RealtyHub.ApiService.Configuration.ContractTemplatesPath
  commentId: P:RealtyHub.ApiService.Configuration.ContractTemplatesPath
  id: ContractTemplatesPath
  parent: RealtyHub.ApiService.Configuration
  langs:
  - csharp
  - vb
  name: ContractTemplatesPath
  nameWithType: Configuration.ContractTemplatesPath
  fullName: RealtyHub.ApiService.Configuration.ContractTemplatesPath
  type: Property
  source:
    remote:
      path: Codigos/RealtyHub/RealtyHub.ApiService/Configuration.cs
      branch: main
      repo: https://github.com/israel-bsi/realtyhub
    id: ContractTemplatesPath
    path: ../RealtyHub.ApiService/Configuration.cs
    startLine: 7
  assemblies:
  - RealtyHub.ApiService
  namespace: RealtyHub.ApiService
  syntax:
    content: public static string ContractTemplatesPath { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property ContractTemplatesPath As String
  overload: RealtyHub.ApiService.Configuration.ContractTemplatesPath*
- uid: RealtyHub.ApiService.Configuration.ReportsPath
  commentId: P:RealtyHub.ApiService.Configuration.ReportsPath
  id: ReportsPath
  parent: RealtyHub.ApiService.Configuration
  langs:
  - csharp
  - vb
  name: ReportsPath
  nameWithType: Configuration.ReportsPath
  fullName: RealtyHub.ApiService.Configuration.ReportsPath
  type: Property
  source:
    remote:
      path: Codigos/RealtyHub/RealtyHub.ApiService/Configuration.cs
      branch: main
      repo: https://github.com/israel-bsi/realtyhub
    id: ReportsPath
    path: ../RealtyHub.ApiService/Configuration.cs
    startLine: 8
  assemblies:
  - RealtyHub.ApiService
  namespace: RealtyHub.ApiService
  syntax:
    content: public static string ReportsPath { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property ReportsPath As String
  overload: RealtyHub.ApiService.Configuration.ReportsPath*
- uid: RealtyHub.ApiService.Configuration.LogosPath
  commentId: P:RealtyHub.ApiService.Configuration.LogosPath
  id: LogosPath
  parent: RealtyHub.ApiService.Configuration
  langs:
  - csharp
  - vb
  name: LogosPath
  nameWithType: Configuration.LogosPath
  fullName: RealtyHub.ApiService.Configuration.LogosPath
  type: Property
  source:
    remote:
      path: Codigos/RealtyHub/RealtyHub.ApiService/Configuration.cs
      branch: main
      repo: https://github.com/israel-bsi/realtyhub
    id: LogosPath
    path: ../RealtyHub.ApiService/Configuration.cs
    startLine: 9
  assemblies:
  - RealtyHub.ApiService
  namespace: RealtyHub.ApiService
  syntax:
    content: public static string LogosPath { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property LogosPath As String
  overload: RealtyHub.ApiService.Configuration.LogosPath*
- uid: RealtyHub.ApiService.Configuration.EmailSettings
  commentId: P:RealtyHub.ApiService.Configuration.EmailSettings
  id: EmailSettings
  parent: RealtyHub.ApiService.Configuration
  langs:
  - csharp
  - vb
  name: EmailSettings
  nameWithType: Configuration.EmailSettings
  fullName: RealtyHub.ApiService.Configuration.EmailSettings
  type: Property
  source:
    remote:
      path: Codigos/RealtyHub/RealtyHub.ApiService/Configuration.cs
      branch: main
      repo: https://github.com/israel-bsi/realtyhub
    id: EmailSettings
    path: ../RealtyHub.ApiService/Configuration.cs
    startLine: 11
  assemblies:
  - RealtyHub.ApiService
  namespace: RealtyHub.ApiService
  syntax:
    content: public static Configuration.EmailConfiguration EmailSettings { get; set; }
    parameters: []
    return:
      type: RealtyHub.ApiService.Configuration.EmailConfiguration
    content.vb: Public Shared Property EmailSettings As Configuration.EmailConfiguration
  overload: RealtyHub.ApiService.Configuration.EmailSettings*
references:
- uid: RealtyHub.ApiService
  commentId: N:RealtyHub.ApiService
  href: RealtyHub.html
  name: RealtyHub.ApiService
  nameWithType: RealtyHub.ApiService
  fullName: RealtyHub.ApiService
  spec.csharp:
  - uid: RealtyHub
    name: RealtyHub
    href: RealtyHub.html
  - name: .
  - uid: RealtyHub.ApiService
    name: ApiService
    href: RealtyHub.ApiService.html
  spec.vb:
  - uid: RealtyHub
    name: RealtyHub
    href: RealtyHub.html
  - name: .
  - uid: RealtyHub.ApiService
    name: ApiService
    href: RealtyHub.ApiService.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: RealtyHub.ApiService.Configuration.ContractsPath*
  commentId: Overload:RealtyHub.ApiService.Configuration.ContractsPath
  href: RealtyHub.ApiService.Configuration.html#RealtyHub_ApiService_Configuration_ContractsPath
  name: ContractsPath
  nameWithType: Configuration.ContractsPath
  fullName: RealtyHub.ApiService.Configuration.ContractsPath
- uid: RealtyHub.ApiService.Configuration.PhotosPath*
  commentId: Overload:RealtyHub.ApiService.Configuration.PhotosPath
  href: RealtyHub.ApiService.Configuration.html#RealtyHub_ApiService_Configuration_PhotosPath
  name: PhotosPath
  nameWithType: Configuration.PhotosPath
  fullName: RealtyHub.ApiService.Configuration.PhotosPath
- uid: RealtyHub.ApiService.Configuration.ContractTemplatesPath*
  commentId: Overload:RealtyHub.ApiService.Configuration.ContractTemplatesPath
  href: RealtyHub.ApiService.Configuration.html#RealtyHub_ApiService_Configuration_ContractTemplatesPath
  name: ContractTemplatesPath
  nameWithType: Configuration.ContractTemplatesPath
  fullName: RealtyHub.ApiService.Configuration.ContractTemplatesPath
- uid: RealtyHub.ApiService.Configuration.ReportsPath*
  commentId: Overload:RealtyHub.ApiService.Configuration.ReportsPath
  href: RealtyHub.ApiService.Configuration.html#RealtyHub_ApiService_Configuration_ReportsPath
  name: ReportsPath
  nameWithType: Configuration.ReportsPath
  fullName: RealtyHub.ApiService.Configuration.ReportsPath
- uid: RealtyHub.ApiService.Configuration.LogosPath*
  commentId: Overload:RealtyHub.ApiService.Configuration.LogosPath
  href: RealtyHub.ApiService.Configuration.html#RealtyHub_ApiService_Configuration_LogosPath
  name: LogosPath
  nameWithType: Configuration.LogosPath
  fullName: RealtyHub.ApiService.Configuration.LogosPath
- uid: RealtyHub.ApiService.Configuration.EmailSettings*
  commentId: Overload:RealtyHub.ApiService.Configuration.EmailSettings
  href: RealtyHub.ApiService.Configuration.html#RealtyHub_ApiService_Configuration_EmailSettings
  name: EmailSettings
  nameWithType: Configuration.EmailSettings
  fullName: RealtyHub.ApiService.Configuration.EmailSettings
- uid: RealtyHub.ApiService.Configuration.EmailConfiguration
  commentId: T:RealtyHub.ApiService.Configuration.EmailConfiguration
  parent: RealtyHub.ApiService
  href: RealtyHub.ApiService.Configuration.html
  name: Configuration.EmailConfiguration
  nameWithType: Configuration.EmailConfiguration
  fullName: RealtyHub.ApiService.Configuration.EmailConfiguration
  spec.csharp:
  - uid: RealtyHub.ApiService.Configuration
    name: Configuration
    href: RealtyHub.ApiService.Configuration.html
  - name: .
  - uid: RealtyHub.ApiService.Configuration.EmailConfiguration
    name: EmailConfiguration
    href: RealtyHub.ApiService.Configuration.EmailConfiguration.html
  spec.vb:
  - uid: RealtyHub.ApiService.Configuration
    name: Configuration
    href: RealtyHub.ApiService.Configuration.html
  - name: .
  - uid: RealtyHub.ApiService.Configuration.EmailConfiguration
    name: EmailConfiguration
    href: RealtyHub.ApiService.Configuration.EmailConfiguration.html
